# Generated by Django 3.1.1 on 2020-09-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_ficha_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='nome_ficha',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
