# Generated by Django 3.1.1 on 2020-09-30 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_ficha_nome_ficha'),
    ]

    operations = [
        migrations.CreateModel(
            name='fichas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.TextField()),
                ('valor', models.IntegerField()),
                ('nome_ficha', models.CharField(max_length=50)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='ficha',
        ),
    ]
